#!/usr/bin/env bash
# Bash script that will display information about subdomains.

information_printer () {
	script=$(dig "${2}.${1}" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "${2} $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 2 ]; then
	information_printer "$1" "$2"
else
	subs=("www" "lb-01" "web-01" "web-02")
	for domain in "${subs[@]}"; do
		information_printer "$1" "$domain"
	done
fi
