#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server:
if [ $# < 3 ]; then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME'
    exit 1
fi


scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
 