#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server:
if [ "$#" -eq 4 ];
then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
else
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME'
fi


 