#!/usr/bin/env bash
# ---

# install the nginx software
sudo apt-get -y upgrade
sudo apt-get -y update
sudo apt-get -y install nginx

# Nginx should list on port 80
sudo sed -i 's/^\(listen 80;\)/\1' /etc/nginx/site-avaiable/default


# create hmtl page with 'hello world'
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Hello World!" | sudo tee /usr/share/nginx/html.index


# configure the nginx redirection
echo "  location /redirect_me {" | sudo tee -a /etc/nginx/sites-available/default
echo "      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" | sudo tee -a /etc/nginx/sites-available/default
echo "}" | sudo tee -a /etc/nginx/sites-available/default

sudo service nginx restart
