#!/usr/bin/env bash

# install the nginx software
sudo apt-get -y upgrade
sudo apt-get -y update
sudo apt-get -y install nginx

# Nginx should list on port 80
sudo sed -i 's/^\(listen 80;\)/\1' /etc/nginx/site-avaiable/default


# create hmtl page with 'hello world'
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Hello World!" | sudo tee /usr/share/nginx/html.index
echo "Ceci n'est pas une page"" | sudo tee /var/www/html/404.html


# configure the nginx redirection
redirect_me = " location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;\n\t\t}\n"
path = "/etc/nginx/sites-enabled/default"

sed -i "/^\tlocation \/ {/i \ $redirect_me" ${path}}

# 404 err using sed -i
error  = "\terror_page 404 /404.html;\n"
sed -i "/^\tlocation \/ {/i \ $error" ${path}}

# restart service
sudo service nginx restart
