#!/usr/bin/env bash

# Install the nginx software
sudo apt-get -y upgrade
sudo apt-get -y update
sudo apt-get -y install nginx

# Nginx should listen on port 80
sudo sed -i 's/^\(listen 80;\)/\1/' /etc/nginx/sites-available/default

# Create HTML page with 'Ceci n'est pas une page'
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure the nginx custom 404 page
echo "error_page 404 /404.html;" | sudo tee -a /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
sudo service nginx restart
