#!/usr/bin/env bash

# Install the nginx software
sudo apt-get -y upgrade
sudo apt-get -y update
sudo apt-get -y install nginx

# Nginx should listen on port 80
sudo sed -i 's/^\(listen 80;\)/\1/' /etc/nginx/sites-available/default

# Create HTML page with 'hello world'
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure the nginx redirection
redirect_me="location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;\n\t}\n"
path="/etc/nginx/sites-available/default"
sudo sed -i "/^\tlocation \/ {/i $redirect_me" ${path}

# 404 error using sed -i
error="error_page 404 /404.html;\n"
sudo sed -i "/^\tlocation \/ {/i $error" ${path}

# Restart service
sudo service nginx restart
