#!/usr/bin/env bash
# config a new server

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "/listen 80 default_server/a    add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
