#!/usr/bin/env bash
# install and config HAproxy

sudo apt-get -y update
sudo apt-get -y install haproxy
echo "frontend http
        bind *:80
        mode http
        default_backend web_backend
    backend web_backend
        balance roundrobin
        server 251454-web-01 54.174.69.148:80 check
        server 251454-web-02 18.204.20.114:80 check " >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
