#!/usr/bin/env bash
# a Bash script that configures a server

apt-get update
apt-get install -y nginx
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
service nginx start
