#!/usr/bin/env bash
# a Bash script that configures a server
# use port 80 for nginx
sed -i 's/[0-9]\+ default_server/80 default_server/' "/etc/nginx/sites-enabled/default"
kill -1 "$(pgrep nginx | head -1)"