#!/usr/bin/env bash
# a Bash script that configures a server

# Configure Nginx to use port 80
sed -i 's/listen [0-9]\+/listen 80/' /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
service nginx restart