#!/usr/bin/env bash
#  This Bash script displays Best School 10 times.
str="Best School"
count=1
while [ $count -le 10 ]
do
    echo "$str"
    if [ "$count" -eq "9" ]
    then
	echo "Hi"
    fi
    count=$((count + 1))
done
