'use strict';(function(){var cmpFile='noModule'in HTMLScriptElement.prototype?'cmp2.js':'cmp2-polyfilled.js';(function(){var cmpScriptElement=document.createElement('script');var firstScript=document.getElementsByTagName('script')[0];cmpScriptElement.async=true;cmpScriptElement.type='text/javascript';var cmpUrl;var tagUrl=document.currentScript.src;cmpUrl='https://cmp.inmobi.com/tcfv2/CMP_FILE?referer=www.databasejournal.com'.replace('CMP_FILE',cmpFile);cmpScriptElement.src=cmpUrl;firstScript.parentNode.insertBefore(cmpScriptElement,firstScript);})();(function(){var css=""
+" .qc-cmp-button { "
+"   background-color: #FFCC00 !important; "
+"   border-color: #FFCC00 !important; "
+" } "
+" .qc-cmp-button:hover { "
+"   border-color: #FFCC00 !important; "
+" } "
+" .qc-cmp-alt-action, "
+" .qc-cmp-link { "
+"   color: #FFCC00 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   background-color: #FFCC00 !important; "
+"   border-color: #FFCC00 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   color: #ffffff !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   color: #969696 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   background-color: #eee !important; "
+"   border-color: transparent !important; "
+" } "
+""
+"";var stylesElement=document.createElement('style');var re=new RegExp('&quote;','g');css=css.replace(re,'"');stylesElement.type='text/css';if(stylesElement.styleSheet){stylesElement.styleSheet.cssText=css;}else{stylesElement.appendChild(document.createTextNode(css));}
var head=document.head||document.getElementsByTagName('head')[0];head.appendChild(stylesElement);})();var autoDetectedLanguage='en';var gvlVersion=2;function splitLang(lang){return lang.length>2?lang.split('-')[0]:lang;};function isSupported(lang){var langs=['en','fr','de','it','es','da','nl','el','hu','pt','pt-br','pt-pt','ro','fi','pl','sk','sv','no','ru','bg','ca','cs','et','hr','lt','lv','mt','sl','tr','zh'];return langs.indexOf(lang)===-1?false:true;};if(gvlVersion===2&&isSupported(splitLang(document.documentElement.lang))){autoDetectedLanguage=splitLang(document.documentElement.lang);}else if(gvlVersion===3&&isSupported(document.documentElement.lang)){autoDetectedLanguage=document.documentElement.lang;}else if(isSupported(splitLang(navigator.language))){autoDetectedLanguage=splitLang(navigator.language);};var choiceMilliSeconds=(new Date).getTime();window.__tcfapi('init',2,function(){},{"coreConfig":{"uspVersion":1,"uspJurisdiction":["CA"],"uspLspact":"N","uspPrivacyPolicyLink":"https://www.databasejournal.com/privacy-policy","uspDeleteDataLink":"https://technologyadvice.com/privacy-policy/ccpa-opt-out-form/","suppressCcpaLinks":false,"inmobiAccountId":"vPn77x7pBG57Y","privacyMode":["GDPR","USP"],"hashCode":"Cclt/lvZ3mag2oK38fZj9A","publisherCountryCode":"US","publisherName":"Database Journal","vendorPurposeIds":[2,3,4,5,6,7,8,9,10,1],"vendorFeaturesIds":[1,3,2],"vendorPurposeLegitimateInterestIds":[2,3,4,5,6,7,8,9,10],"vendorSpecialFeaturesIds":[1,2],"vendorSpecialPurposesIds":[1,2],"googleEnabled":true,"consentScope":"service","thirdPartyStorageType":"iframe","consentOnSafari":false,"displayUi":"inEU","defaultToggleValue":"off","initScreenRejectButtonShowing":false,"softOptInEnabled":false,"showSummaryView":true,"persistentConsentLinkLocation":4,"displayPersistentConsentLink":true,"uiLayout":"banner","publisherLogo":"https://www.databasejournal.com/img/logo.gif","vendorListUpdateFreq":30,"publisherPurposeIds":[1,10,2,3,4,7,8,9],"initScreenBodyTextOption":1,"publisherConsentRestrictionIds":[],"publisherLIRestrictionIds":[],"publisherPurposeLegitimateInterestIds":[],"publisherSpecialPurposesIds":[1,2],"publisherFeaturesIds":[1,2,3],"publisherSpecialFeaturesIds":[1,2],"stacks":[1,42],"lang_":"en","gvlVersion":2},"premiumUiLabels":{"uspPrivacyPolicyLinkText":"Privacy Policy","uspDeleteDataLinkText":"CCPA Opt-Out Form"},"premiumProperties":{"googleWhitelist":[1]},"coreUiLabels":{},"theme":{"uxPrimaryButtonColor":"#FFCC00","uxSecondaryButtonTextColor":"#969696"},"nonIabVendorsInfo":{"nonIabVendorList":[{"vendorId":2,"pCode":"vPn77x7pBG57Y","name":"ZoomInfo","description":"ZoomInfo combines the leading business contact database with best-in-class tech to pinpoint your customers & deliver the intelligence you need to hit your number.","privacyPolicyUrl":"https://www.zoominfo.com/about-zoominfo/privacy-center","nonIabPurposeConsentIds":[1,2,3,4,5,6,7,8,9,10],"nonIabPurposeLegitimateInterestIds":[],"active":null},{"vendorId":3,"pCode":"vPn77x7pBG57Y","name":"Intentsify, LLC","description":"Intentsify makes intent data actionable, automating the way B2B marketing teams aggregate, digest, and act on prospects' buying signals.","privacyPolicyUrl":"https://intentsify.io/privacy-policy/","nonIabPurposeConsentIds":[1,10,2,3,4,5,6,7,8,9],"nonIabPurposeLegitimateInterestIds":[],"active":null}]}});})();